# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmSwiftSample
  pod 'RealmSwift'

  target 'RealmSwiftSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealmSwiftSampleUITests' do
    # Pods for testing
  end

end
