# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya'
  pod 'RxSwift'
  pod 'Moya/RxSwift'

  # Pods for MoyaSample

  target 'MoyaSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoyaSampleUITests' do
    # Pods for testing
  end

end
